### ISSUE TITLE
Version 1.9.1 Does Not Upload Properly to VRChat

### ISSUE THREAD

**Issue by Voxian** [VRLabs/Final-IK-Stub#7]
I have been using this stub in many of my projects for use with VRChat. 

However, in the latest release, the files were moved into a different folder structure and reorganized as a creator companion package. 

Even though my projects still link to these scripts properly, they do not upload correctly to VRChat. The result in game appears to have no scripts installed at all.

For the time being, I am asking my customers to continue to use the older version of the script. Please take a look at this issue and let me know what you think or if I need to make changes on my end.

I normally develop using the official release of Final IK and then my customers use the stub to upload.

I can confirm that nothing about my project has changed and my project still works correctly on the original release of the stub.

**Comment by Cibbi** [comment]
Yes, our recent adaptation of scripts to work with vcc did change the folder structure and we *may have broken stuff*

We're working on a solution for both this and the dynamic bones stub (for the unitypackage we just need to put the script back where it was, but for the vcc version we *will need some more creativity*)

For the time being use the older version, effectively the latest releases were only to keep the repository structure the same as the other packages with the vcc update.

I'll come back here once we released the fixed versions

**Comment by Voxian** [comment]
Thank you for confirming that you are aware of this issue. I'll continue to direct people to use the older version until there is a fix.

I do understand the need to move this over to the VCC packages section, and I hope there is a solution that will work going forwards. I prefer to use VCC packages when possible.

**Comment by Cibbi** [comment]
1.9.2 is released, with the fix for the upload issue.

Also as a nice bonus now it won't nuke a full Final IK installation if it finds one.
